### ISSUE TITLE
Incorrect code in solution

### ISSUE THREAD

**Issue by DRyanMiller** [learn-co-curriculum/dsc-text-classification-lab#1]
The function 'process_article' is not correctly coded in the solution. The code in the solution does not remove all of the stopwords. (See the list of words provided in the solution following the application of this function. There you will see the word 'the' appears 3702 times.) 

The error in the code comes occurs with the inclusion of .lower() in this line:
stopwords_removed = [token.lower() for token in tokens if token not in stopwords_list].

The error occurs because the stopwords are all lowercase. 

To correct the error, try the following:

def process_article(article):
    tokenized = nltk.word_tokenize(article)
    tokenized_lower = [token.lower() for token in tokenized]
    tokenized_stopped = [token for token in tokenized_lower if token not in stopwords_list]
    return tokenized_stopped

**Comment by lmcm18** [comment]
Fixed. Thanks @DRyanMiller ! After correcting this function, the size of the vocabulary changed, which was also fixed in the notebook.
